services:
  envoy:
    image: envoyproxy/envoy:v1.33.0
    container_name: embracer-envoy
    ports:
      - "10000:10000"       # Envoy 클라이언트 수신 포트
      - "19000:19000"       # Envoy Admin API 포트
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "debug"]
    depends_on:
      - control-plane
    networks:
      - embracer_net

  control-plane:
    image: embracer_control_plane:latest  # Dockerfile 위치
    container_name: embracer-control-plane
    ports:
      - "18000:18000"            # gRPC xDS 포트
    networks:
      - embracer_net
    restart: unless-stopped

  embracer:
    image: embracer:latest
    hostname: embracer
    container_name: embracer
    environment:
      - embracer_SERVICE=test_dynamic_service
      - embracer_ADDR=embracer:8080
      - CONTROL_PLANE_HOST=embracer-control-plane
    depends_on:
      - control-plane
    networks:
      - embracer_net

  kafka:
    image: embracer_kafka:latest
    hostname: embracer-kafka
    container_name: embracer-kafka
    ports:
      - "9092:9092"  # Kafka Client
      - "9093:9093"  # Controller Listener
      - "9101:9101"  # JMX (Optional)
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"
    volumes:
      - kafka-data:/var/lib/kafka/data:rw
    environment:
      KAFKA_CLUSTER_ID: "my-kraft-cluster"
    networks:
      - embracer_net
    restart: unless-stopped

  akhq:
    image: tchiotludo/akhq:latest
    container_name: akhq
    ports:
      - "8090:8080"
    networks:
      - embracer_net
    depends_on:
      - kafka
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          server:
            servlet:
              context-path: /
          connections:
            astron-kafka:
              properties:
                bootstrap.servers: "embracer-kafka:9092"


volumes:
  kafka-data:
    driver: local

networks:
  embracer_net: